CLINIC_LIST = [
        "Ambulance Service", "Prestige Wellness Center", "Dermatology and Plastic Surgery Center",
        "Breast Center", "Breast Feeding Clinic", "Cardiac Care Unit", "Cardiac Cath Lab",
        "Cardiac Rehabilitations", "Dental Cosmetic and Implant Center", "Diabetes Mellitus (DM) & Endocrinology Center",
        "Diagnostic Imaging Dept (JTH)", "Ear Nose Throat Center", "Emergency Medical Service Center",
        "Emergency & Accident Dept(JTH)", "Eye Center", "Fertility Center", "Gastrointestinal & Liver Center",
        "Gastrointestinal", "Health Promotion Center", "Hearing Speech Balance Tinnitus Center",
        "Heart Center", "Hemodialysis Center", "Hyperbaric Oxygen Therapy",
        "Diagnostic Imaging and Interventional Radiology Center", "ICU - Trauma and Surgery",
        "Intermediate Intensive Care", "Laboratory", "Labour Room", "Lasik and SuperSight Surgery Center",
        "Internal Medicine Center", "Mental Health Center", "Neonatal Intensive Care Unit (NICU)",
        "Neuroscience Center", "Nursery", "Women's Health Center", "Oncology Center",
        "Operating Room", "Orthopedic Center", "Pediatric Intensive Care Unit or PICU",
        "Child Health Center", "Rehabilitation Center", "Surgery Center", "Urology Center",
        "Wound Care Unit", "Hospital Director Office", "Medical Staff Organization",
        "Anesthetic", "BPH Clinic : Bangsare", "BPH Clinic : Bo Win",
        "BPH Clinic : Kreua Sahaphat", "ICU Medicine", "ICU Neurosciences",
        "KOH LARN Clinic", "Nutrition Therapeutic", "U-Tapao Clinic", "Jomtien Hospital",
    ]

CLINIC_NAME_MAP = {
        "แผนกเคลื่อนย้ายผู้ป่วยทางการแพทย์": "Ambulance Service",
        "ศูนย์ส่งเสริมสุขภาพ": "Prestige Wellness Center",
        "ศูนย์ผิวพรรณและศัลยกรรมความงาม": "Dermatology and Plastic Surgery Center",
        "ศูนย์เต้านม": "Breast Center",
        "ศูนย์สุขภาพสตรี": "Breast Feeding Clinic",
        "ศูนย์หัวใจ": "Cardiac Care Unit",
        "ศูนย์ทันตกรรมความงามและรากเทียม": "Dental Cosmetic and Implant Center",
        "ศูนย์เบาหวานและต่อมไร้ท่อ": "Diabetes Mellitus (DM) & Endocrinology Center",
        "ศูนย์วินิจฉัยและรังสีร่วมรักษา": "Diagnostic Imaging Dept (JTH)",
        "ศูนย์หู คอ จมูก": "Ear Nose Throat Center",
        "แผนกฉุกเฉิน": "Emergency Medical Service Center",
        "ศูนย์ตา": "Eye Center",
        "ศูนย์มีบุตรยาก": "Fertility Center",
        "ศูนย์ระบบทางเดินอาหารและตับ": "Gastrointestinal & Liver Center",
        "ศูนย์เวชศาสตร์ฟื้นฟู": "Rehabilitation Center",
        "ศูนย์สมองและระบบประสาท": "Neuroscience Center",
        "ศูนย์สุขภาพจิต": "Mental Health Center",
        "ศูนย์อายุรกรรมทั่วไป": "Internal Medicine Center",
        "ศูนย์ศัลยกรรมทั่วไป": "Surgery Center",
        "ศูนย์ศัลยกรรมกระดูกและข้อ": "Orthopedic Center",
        "ศูนย์กุมารเวช": "Child Health Center",
        "ศูนย์ศัลยกรรมระบบทางเดินปัสสาวะ": "Urology Center",
        "ศูนย์โรคมะเร็ง": "Oncology Center",
        "ศูนย์แก้ไขสายตาด้วยเลสิคและซุปเปอร์ไซต์": "Lasik and SuperSight Surgery Center",
        "ศูนย์ดูแลแผล": "Wound Care Unit",
        "ศูนย์โภชนบำบัด": "Nutrition Therapeutic",
        "ศูนย์สุขภาพสตรี": "Women's Health Center",
    }