services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn filemanager.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: filemanager.settings
      - key: SECRET_KEY
        generateValue: true
