services:
  - type: web
    name: dashboard-bph
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn filemanager.wsgi
    envVars:
      - key: SECRET_KEY
        value: "your_secret_key_here"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "summary-inquiry.onrender.com"
