# Generated by Django 5.2.3 on 2025-06-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='analyzed',
        ),
    ]
