# Generated by Django 5.2.6 on 2025-09-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "main_uploadedfile" RENAME COLUMN "url" TO "file";',
            reverse_sql='ALTER TABLE "main_uploadedfile" RENAME COLUMN "file" TO "url";'
        ),
    ]
